### ISSUE TITLE
Plugin is failing to fetch metadata for some series

### ISSUE THREAD

**Issue by Evil-Crab** [MediaBrowser/Emby.Plugins.AniList#2]
AniList plugin is failing to fetch metadata for some series (e.g. [Gintama ](https://anilist.co/anime/918/Gintama/)).

Here's the error from the server logs
https://gist.github.com/Evil-Crab/e18cdd8053cabcc6042ac50f0b15f4b7

**Comment by maus-me** [comment]
Issue also persists into 4.8.0.21, and also effects Windows installs as well.

In a library of about 1100 series, I have approx. 400 having this issue on each metadata refresh.

https://gist.github.com/nullip/9733ba91f1e2d47aab26ac866c9cb189

**Comment by maus-me** [comment]
After repeated testing I can confirm the cause of this issue is related to these lines in AniListMetadataProvider.cs,

```
if (Equals_check.Compare_strings("youtube", WebContent.data.Media.trailer.site)) {
                result.Item.AddTrailerUrl("https://youtube.com/watch?v=" + WebContent.data.Media.trailer.id);
}
```
https://github.com/MediaBrowser/Emby.Plugins.AniList/blob/master/Emby.Plugins.AniList/AniListMetadataProvider.cs

Any AniList page missing a youtube trailer will fail to pull metadata.  Not diving into the logic of this check but simply adding a try { } catch(exception){} around this function allows the rest of this to continue to function as normal.

**Comment by LukePulverenti** [comment]
Thanks, I'll push an update to the plugin.
